### ISSUE TITLE
detecting that app is running in ripple emulator

### ISSUE THREAD

**Issue by myusrn** [ripple-emulator/ripple#10]
is there a recommended navigator.userAgent.test() or other check that one should use to determine at runtime that your cordova app is running in the ripple emulator vs in a device specific emulator or on a specific device?

**Comment by KODerFunk** [comment]
I use [before-cordova.js](https://gist.github.com/KODerFunk/63eab47efe570ec32204) in my app for stubbing unsupported plugins in Ripple.

**Comment by myusrn** [comment]
thanks for response and library suggestion.  i ended up going with the following implementation. 

```
    // determines if current runtime environment is ripple emulator
    export function isRippleEmulator() {
        if (window.parent && window.parent['ripple']) { return true; } else { return false; } // or return !!(window.parent && window.parent['ripple']);
        //if (window.tinyHippos != undefined) { return true; } else { return false; }
        //if (!!document.getElementById("tinyhippos-injected") && !!window.top.require) { return true; } else { return false; }
        //if (navigator.userAgent.match(/(Android|BlackBerry|Edge|IEMobile|iPad|iPhone|iPod)/)) { return false; } else { return true; }
// using window.parent['ripple'] in lieu of window.parent.ripple to get around typescript "Property 'ripple' does not exist on type 'Window'"
// ripple android  = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
// ripple ios      = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
// android google  = Mozilla/5.0 (Linux; Android 4.4.4; sdk Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36
// android vstudio = ???
// win bigscreen   = Mozilla/5.0 (Windows NT 10.0; Win64; x64; MSAppHost/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
// win mobile      = ???
    }
```

**Comment by TimBarham** [comment]
Yep, checking `window.parent && window.parent.ripple` (or `window.parent && window.parent['ripple']` if your in TypeScript and the compiler complains about `.ripple`) is the best way to check.

**Comment by TimBarham** [comment]
FYI @KODerFunk... I just committed a change that will stop Ripple displaying the "I Haz Cheeseburger" dialog for *any* Cordova `exec` call that doesn't provide either `success` or `fail` callbacks. This prevents it for most of the calls made by the status bar and keyboard plugins, and also the screen orientation plugin your stub handles.

I'm about to commit a change that handles the specific status bar and keyboard calls that do provide callbacks.
